from turtle import *
def curvemove():
    print(u"\u25A0"*5)
    print(" DIL")
    for i in range(200):
        right(1)
        forward(1)
color('red','green')        
begin_fill()
left(150)
forward(111.65)
curvemove()
left(100)
curvemove()
forward(90)
print(" Pakistan")
print(u"\u250"*10)
print(" LOLLL")
print(u"\u250"*7)
end_fill()
done()
